services:
  cside-challenge:
    container_name: cside-challenge
    image: cside-challenge
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      VIRTUAL_HOST: cside-challenge.rigoli.dev
      VIRTUAL_PORT: 8080
# networks:
#   default:
#     external: true
#     name: proxy
